server:
  port: 8781

# 指定注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# 指定当前服务的名称
spring:
  application:
    name: order-service
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 2000

# Server端，设置 ribbon 策略 (自定义负载均衡策略)
product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 修改调用超时时间，单位ms, 大部分超时时间不超过2s
# openFeign options 默认超时时间是60s，但是由于有熔断Hystrix，所以1s就凉了
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000